### ISSUE TITLE
AutryMakers_new:Nationality

### ISSUE THREAD

**Issue by steads** [american-art/autry#33] opened 2016-07-05 12:18 UTC
Nationality: The mapping of this field would appear correct until the actual data is reviewed. Here it can be seen that it is a mixture of (please note the use of E21 Not E39)
E21 ->P107i ->E74
And entries relating an instance of E67 Birth to the place of birth or entries relating an instance of F51 Pursuit to the place where it was conducted (Please note that they all use the appellation of the place; which are generally not characteristic instances of E44 Place Appellation).

**Comment by mayaram00** [comment] 2016-09-09 22:56
This looks like an issue with the museum data.

**Comment by workergnome** [comment] 2016-09-10 00:02
Maya—what is the issue with the museum data?  I'm not sure there's quite enough information here to merit closing this issue.

**Comment by caknoblock** [comment] 2016-09-10 00:07
We can leave the issue open, but Maya wanted to indicate that this is an issue that we (USC) cannot address.  Do want us to simply leave a comment on such issues that it is up to the museum to make thees changes to their data?

**Comment by workergnome** [comment] 2016-09-10 00:10
It might make sense to leave it open, and let the museum close it if they're not going to address the issue.  More so, I think it might be important to explain to the museum what the issue is, and what would be needed to resolve it.

**Comment by caknoblock** [comment] 2016-09-11 00:06
Okay, i'm reopening this issue for the museum to address.  This field contains a mix of nationality, race, place of birth, and where they were active.  Ideally, these should be separated into different fields.  Since most of them are nationalities, we will model it as such.

**Comment by AutryIT** [comment] 2016-09-12 15:34
I could probably clean it up a little.  I guess I would add a field or two.  Is it too late to do so?

**Comment by caknoblock** [comment] 2016-09-12 18:32
Let’s hold off on having you fix this data until we see what is really needed for the browse application.

**Comment by mayaram00** [comment] 2016-09-16 03:05
In the future I'll leave the comment open! Apologies for the confusion.

**Closed as completed** 2016-11-18 23:13 UTC
