### ISSUE TITLE
The ULAN_ID in Autry should somehow be modeled as a ULAN ID

### ISSUE THREAD

**Issue by caknoblock** [american-art/autry#17] opened 2016-04-21 18:17 UTC
I'm not sure exactly how to do this.

@vladimir, can you provide some guidance here

**Comment by mayaram00** [comment] 2016-09-16 04:46
Unsure how to proceed – was this resolved in April? It looks as though ULAN_ID was mapped in the data sets where it appeared.

**Comment by mayaram00** [comment] 2016-09-27 21:12
Duplicate of #34

**Closed as completed by mayaram00** 2016-09-27 21:12 UTC
